version: "3"

services:
    influxdb:
        build: ./influxdb
        container_name: influxdb
        ports:
            - 8086:8086
        volumes: #Para guradar los datos 
            - /var/lib/influxdb:/var/lib/influxdb
        
    telegraf:
        image: telegraf:1.34.4
        container_name: telegraf
        volummes: 
            - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
        links: 
            - "container:influxdb"

    grafana: 
        image: grafana
        container_name: grafana
        ports: 
            - 3000:3000


